# Generated by Django 4.2.2 on 2023-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='numero_telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
