# Generated by Django 4.2.2 on 2023-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='estado_credencial',
            field=models.CharField(choices=[('activa', 'activa'), ('inactiva', 'inactiva')], default='inactiva', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudcredencial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('aprobada', 'aprobada'), ('rechazada', 'rechazada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcredencial',
            name='tipo_solicitud',
            field=models.CharField(choices=[('nueva', 'nueva'), ('reposicion', 'reposicion')], max_length=20),
        ),
    ]
