# Generated by Django 4.2.2 on 2023-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuariopersonalizado_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='estado_credencial',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10),
        ),
    ]
